### ISSUE TITLE
Build Failure on Android Studio (Win 11)

### ISSUE THREAD

**Issue by ygtorres** [FluidSynth/fluidsynth#1242]
this is part of the exception 

 ```
FATAL EXCEPTION: main
                                     Process: com.posu.pocket.pocketcomposerai, PID: 2759
                                     java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found: needed by /data/app/~~iuABFymb7V4Jsd7GvWy_tA==/com.posu.pocket.pocketcomposerai-uXH95-N2mBKU6af81eUW0g==/base.apk!/lib/arm64-v8a/libfluidsynth.so in namespace classloader-namespace
                                     	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                     	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                     	at java.lang.System.loadLibrary(System.java:1656)
                                     
```

**Comment by derselbst** [comment]
Duplicate of https://github.com/FluidSynth/fluidsynth/issues/1222#issuecomment-1469658193
