### ISSUE TITLE
cannot import name 'Note' from 'note'

### ISSUE THREAD

**Issue by MaksGrabowy** [FluidSynth/fluidsynth#525]
I am using windows 10 and Spyder with Python 3.7. my code is just:
`from mingus.midi import fluidsynth`
The whole error looks like this:

runfile('C:/Users/admin/untitled11.py', wdir='C:/Users/admin')
Traceback (most recent call last):

  File "<ipython-input-61-29700770bc45>", line 1, in <module>
    runfile('C:/Users/admin/untitled11.py', wdir='C:/Users/admin')

  File "C:\Conda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Conda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/admin/untitled11.py", line 1, in <module>
    from mingus.midi import fluidsynth

  File "C:\Conda\lib\site-packages\mingus\midi\fluidsynth.py", line 34, in <module>
    from mingus.midi.sequencer import Sequencer

  File "C:\Conda\lib\site-packages\mingus\midi\sequencer.py", line 31, in <module>
    from mingus.containers.instrument import MidiInstrument

  File "C:\Conda\lib\site-packages\mingus\containers\__init__.py", line 20, in <module>
    from note import Note

ImportError: cannot import name 'Note' from 'note' (C:\Conda\lib\site-packages\note\__init__.py)

**Comment by derselbst** [comment]
This isn't a fluidsynth issue.
